services:
  db:
    image: postgres:16-alpine
    container_name: lebronator-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lebronator
    ports:
      - "5432:5432"
    volumes:
      - lebronator_pg:/var/lib/postgresql/data

volumes:
  lebronator_pg:
